#ifndef ERROR_ILST_ESMACAT_H
#define ERROR_ILST_ESMACAT_H

enum esmacat_err{
    NO_ERR = 0,
    //ESMACAT slave application error
    ERR_ESMACAT_SLAVE_DOES_NOT_MATCH = 1001,
    //Motor driver error list
    ERR_MOTOR_DRIVER_NO_DIRECTION_CHANGE_AT_NON_DIRECT_CONTROL = 2001,
    ERR_MOTOR_DRIVER_NO_PWM_CHANGE_AT_NON_DIRECT_CONTROL = 2002,
    ERR_MOTOR_DRIVER_MAX_PWM_REACHED = 2003,
    ERR_MOTOR_DRIVER_MIN_PWM_REACHED = 2004,
    ERR_MOTOR_DRIVER_OUT_OF_SET_VALUE_RANGE = 2005,
    ERR_MOTOR_DRIVER_OUT_OF_EXT_ANALOG_INPUT_INDEX = 2006,
    ERR_MOTOR_DRIVER_OUT_OF_ESCON_ANALOG_INPUT_INDEX = 2007,
    ERR_MOTOR_DRIVER_POS_CONTROL_MODE_IS_DISABLED = 2008,
    ERR_MOTOR_DRIVER_TORQUE_CONTROL_MODE_IS_DISABLED = 2009,
    ERR_MOTOR_DRIVER_INSUFFICIENT_PARAMETER= 2010,
    ERR_MOTOR_DRIVER_PARAMETER_NOT_READY= 2011,
    //Loadcell interface error list
    ERR_LOADCELL_INTERF_OUT_OF_CHANNEL = 3001,
    //Anlaog input error list
    ERR_ANALOG_INPUT_OUT_OF_CHANNEL = 4001,
    ERR_ANALOG_INPUT_NO_SUCH_CONFIG = 4002,
    ERR_ANALOG_INPUT_NOT_SINGLE_ENDED = 4003
};


#endif // ERROR_ILST_ESMACAT_H
